spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/listing
    username: postgres
    password: Pamplemousse345!
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
        hibernate:
          format_sql: true
  data:
    redis:
      host: redis-19351.c14.us-east-1-3.ec2.cloud.redislabs.com
      port: 19351
      password: Rfh9NS2cxqSSHGQ7eDTg2HRIiIJYPJnQ