spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: listing-bot
  data:
    redis:
      url: ${REDIS_URL}
  jpa:
    hibernate:
      ddl-auto: update